server:
  port: 8080
spring:
  mvc:
    #static-path-pattern: /static/**
  datasource:
    username: root
    password: RUYI624713
    url: jdbc:mysql://127.0.0.1:3306/account?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
